### PR TITLE
Add example sharing local state between components

### PR DESCRIPTION
**Pull request by afc163**
- https://twitter.com/AntDesignUI/status/1189803756323405831
- https://codesandbox.io/s/antd-reproduction-template-knr9g

### CODE REVIEW

**Comment by afc163** [comment]
fixed

**Comment by quietshu** [comment]
Thanks! 

This is an interesting use case which uses SWR for global state management (like Redux). But currently SWR revalidates itself constantly (e.g.: on focus / new component being added, etc.) and will be set to `initialStore`.

I think we can add an option to support this use case better (turn off revalidation completely).

**Comment by afc163** [comment]
Yeah, it is a tricky usage and I am happy to show potential of swr in multiple ways.

**Comment by quietshu** [comment]
Although it can be supported with a `latestState` object like this: https://github.com/zeit/swr#subscription-eg-socketio

**Comment by afc163** [comment]
Any chance to merge this?

**Comment by quietshu** [comment]
@afc163 can you delete yarn.lock? And I’ll merge it. 👍 

Although we’ll keep improving the example in the future.

**Pull request merged**
