### PR TITLE
Minor documentation improvements

### PR DESCRIPTION
**Pull request by akx**
I found the docs for `mutate` a little lacking, so here's a couple small improvements.

Closes #322.

### CODE REVIEW

**Comment by quietshu** [comment]
Thank you @akx!

**Comment by jan-paulus** [comment]
Would be good to also update the usage examples within the read me.

**Comment by quietshu** [comment]
Oops we have some conflicts, could you help fix them? @akx

**Comment by jan-paulus** [comment]
Created a new PR including the example update.

See: #322

**Comment by akx** [comment]
@quietshu Rebased (with `compare(a, b)` now also having a signature).

Also added @jan-paulus' example from #322.

**Comment by quietshu** [comment]
Thank you @akx @jan-paulus !

**Pull request merged**
