### PR TITLE
fix: disable dedupe when trigger/mutate (#271)

### LINKED ISSUE #271: [Question]: is it as designed that trigger and mutate will follow dedupingInterval
Hey,

small question: is it as designed, that a manual trigger will follow the `dedupingInterval` and don't invalidate the cached item if it was less than the `dedupingInterval`?

Example: https://codesandbox.io/s/quirky-albattani-ttfrw

Expected: On each button click the new time will be fetched

Actual: It only will be fetched if I click slower than 200ms (default `dedupingInterval`)

Version: 0.1.17

### PR DESCRIPTION
**Pull request by rtxu**
fix #271

### CODE REVIEW

**Comment by rtxu** [comment]
Here is a test demo

[Edit swr_user_experience](https://codesandbox.io/s/swruserexperience-7glnd?fontsize=14&hidenavigation=1&theme=dark)

**Comment by mxschmitt** [comment]
@rtxu I've duplicated two working tests for trigger and mutate and added there a `dedupingInterval` to show that the fix is working.

**Comment by quietshu** [comment]
Thank you @rtxu and @mxschmitt !

**Comment by Tom-Goji** [comment]
This change is exactly what we were looking for thanks 👍 

@shuding It looks like it should have made it into either the 0.5.0 or 0.5.1 tags but I can't see it in either. Has this been held back from release? https://github.com/vercel/swr/commits/0.5.1

**Comment by shuding** [comment]
@Tom-Goji I don’t think this was held back, are you seeing the same bug with the latest release? If so feel free to open a new issue with reproduction, thank you!

**Pull request merged**
